### ISSUE TITLE
Can I reuse this?

### ISSUE THREAD

**Issue by adswa** [vsoch/docker-pull#2]
Hi @vsoch, thanks a lot for putting this together and sharing it - I think this is great. I would like to use it, too, but couldn't find a license and was hence reluctant to just go ahead and take it. Are you fine with me or others deploying your workflow in our own repos?

**Comment by vsoch** [comment]
Oh I’d be happy to add a simple license!

**Comment by vsoch** [comment]
All set! Thanks for the reminder, and enjoy the recipe!

**Comment by adswa** [comment]
Thank you!
