### ISSUE TITLE
Problems with docker compose

### ISSUE THREAD

**Issue by mpozuelo-flomics** [vsoch/docker-pull#4]
Hi! When trying to build the yml as follows:
`sudo docker-compose .github/workflows/pull.yml build`
I get the following error: 
ERROR: In file './.github/workflows/pull.yml', service 'name' must be a mapping not a string.
I've been googleling this and I find that this could be related to a syntax error but I have never used it, and I cannot find the error. Maybe I'm doing something wrong (it's my first time using docker-compose and yml files)
Any help would be appreciated!
Thanks!

**Comment by vsoch** [comment]
Why are you using docker-compose with a GitHub workflow? This doesn't make sense to me.

**Comment by vsoch** [comment]
This is a GitHub workflow (akin to a GitHub action in the repository) you can read about [here](https://docs.github.com/en/actions). The file being yaml does not indicate it's made for docker compose, yaml is akin to json and is a way to structure data, used across different applications.

**Comment by mpozuelo-flomics** [comment]
ok! thanks! didn't know about this. sorry!

**Comment by vsoch** [comment]
No worries! The way this works is that you can copy the workflow file and put it in the same location in one of your repositories, and then update the repos.txt with your containers and it should work with GitHub actions. Good luck!
